spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: psql
    password: psql

  jpa:
    hibernate:
      ddl-auto: none
  data:
    mongodb:
      uri: mongodb://localhost:27017/products_db

#  liquibase:
#    enabled: false

#  mail:
#    host:
#    port:
#    password:
#    username:

server:
  port: 8080
