spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:http://localhost:5432/shop_db
    username: psql
    password: psql
  jpa:
    hibernate:
      ddl-auto: none
#  liquibase:
#    enabled: false

#  mail:
#    host:
#    port:
#    password:
#    username:

server:
  port: 8080
