spring:
  application:
    name: ShopService
  datasource:
    url: ${POSTGRES_URL}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
jwt:
  secret-key: ${JWT_SECRET}
  access-token:
    ttl-millis: ${JWT_ACC_TTL}
  refresh-token:
    ttl-millis: ${JWT_REF_TTL}

server:
  port: 8080
